name: Java Maven Build 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  cloud: aws-cloud
jobs:
  build_test:
    runs-on: ubuntu-latest
    environment:
      name: staging
    env:
      region: us-east-1
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          mvn -B package --file pom.xml
          echo "$name $cloud is running in $region"
          echo "This is example of repo variable ${{vars.PROJECTSCOPE}}"
          echo "this is secret variable ${{secrets.MY_SECRET}}"
          echo "this is example of environment ${{vars.PROJECTID}}"
         
      env:
       name: hello




   
  
