name: Java Maven Build 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    environment: production
         
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          mvn clean install
    - name: run test
      run:  mvn test
    - run: mkdir artifacts && cp target/*.jar artifacts
    - name: upload artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: artifacts
        path: artifacts
    
    
    
        
    





   
  
