name: Java Maven Build 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
 cloud: aws-cloud
jobs:
  build_test:
    runs-on: ubuntu-latest
    environment: production
    env:
      region: us-east-1
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          mvn clean install
    - name: Enable Debug Logging
      run: echo 'ACTIONS_RUNNER_DEBUG=true' >> $GITHUB_ENV

    - name: run test
      run: |
            mvn test
            echo "$name $cloud is deployed in $region"
            echo "this is example for repovariable ${{vars.PROJECTSCOPE}}"
            echo "this is example for secrets ${{secrets.AWS_S3_BUCKET}}
            echo "this is repo ${{vars.PROJECTIDS}}"
            echo "we are deploying to ${{matrix.environment}}"
            echo "githubevent name: ${{github.event_name}}"
      env:
       name: hello

    
    
    
    
        
    





   
  
