

name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  cloud: aws-cloud
 

jobs:
  build_test:

    runs-on: ubuntu-latest
    env:
     name: rupa
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          mvn -B package --file pom.xml
          echo "$cloud is used by $name in $region
      env:
       region: us-east-1

   
  
