name: Java Maven Build 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  cloud: aws-cloud
  
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         environment: [staging,production]
    env:
     region: us-east-1
         
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set environment-specific PROJECTID
      run: |
        echo "Setting PROJECTID for ${{ matrix.environment }}"
        if [[ "${{ matrix.environment }}" == "staging" ]]; then
          echo "PROJECTID=staging-project-id" >> $GITHUB_ENV
        elif [[ "${{ matrix.environment }}" == "production" ]]; then
          echo "PROJECTID=production-project-id" >> $GITHUB_ENV
        fi
    - name: Build with Maven
      run: mvn clean install
    - name: run test
      run: |
           mvn test
           echo "$name $cloud is hosted in $region"
           echo " This is example for repolevel ${{vars.PROJECT}}"
           echo "This is example for secrets ${{secrets.AWS_ACCESS_KEY_ID}}"
           echo "we are deploying to $PROJECTID"
           
      env:
       name: hello
    
    
    
    
        
    





   
  
