name: Java Maven Build & Publish Artifact
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  cloud: aws-cloud
jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
     region: us-east-1
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          mvn -B package --file pom.xml
          echo "$name we are using $cloud in $region region"
          echo "this is example for repolevelconfiguration ${{vars.PROJECTSCOPE}}"
          echo "This is example for secret variables ${{secrets.MY_SECRET}}"
          echo "deploying this project to $environment with ${{vars.PROJECTID}}
      env:
       name: hello


   
  
